version: '3.8'

services:
  directus_db:
    image: postgres:15
    container_name: directus_db
    environment:
      POSTGRES_DB: directus_test_db
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directuspass
    volumes:
      - directus_pgdata:/var/lib/postgresql/data
    networks:
      - directus_network

  directus:
    image: directus/directus:latest
    container_name: directus
    ports:
      - "8055:8055"
    environment:
      SECRET: directus
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: "123"
      DB_CLIENT: pg
      DB_HOST: directus_db
      DB_PORT: "5432"
      DB_DATABASE: directus_test_db
      DB_USER: directus
      DB_PASSWORD: directuspass
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - directus_db
    networks:
      - directus_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminDirectus
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - directus_db
    networks:
      - directus_network

  nest:
    image: shop-directus-nestjs:latest
    container_name: shop_directus_nest_test_1
    ports:
      - "9939:9939"
    depends_on:
      - directus
    networks:
      - directus_network
      
volumes:
  directus_pgdata:

networks:
  directus_network:
    driver: bridge
